// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUgRAwba375i9K4Bm5kNoJRS1Y2sIQa3Q',
    appId: '1:442091398232:web:361dd05d0be7e30b24562d',
    messagingSenderId: '442091398232',
    projectId: 'farmer-market-ee034',
    authDomain: 'farmer-market-ee034.firebaseapp.com',
    storageBucket: 'farmer-market-ee034.firebasestorage.app',
    measurementId: 'G-9LYV2529E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFGyvECdIY4kWLwE0M6VCpDVg4qkXDaY',
    appId: '1:442091398232:android:a2a0f32a19b8507624562d',
    messagingSenderId: '442091398232',
    projectId: 'farmer-market-ee034',
    storageBucket: 'farmer-market-ee034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCph6Mkj1AJTivGEwtYNtdxcDM-0t-CE0c',
    appId: '1:442091398232:ios:8163a8ab8288082324562d',
    messagingSenderId: '442091398232',
    projectId: 'farmer-market-ee034',
    storageBucket: 'farmer-market-ee034.firebasestorage.app',
    iosBundleId: 'com.example.farmermarket.farmerMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCph6Mkj1AJTivGEwtYNtdxcDM-0t-CE0c',
    appId: '1:442091398232:ios:8163a8ab8288082324562d',
    messagingSenderId: '442091398232',
    projectId: 'farmer-market-ee034',
    storageBucket: 'farmer-market-ee034.firebasestorage.app',
    iosBundleId: 'com.example.farmermarket.farmerMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUgRAwba375i9K4Bm5kNoJRS1Y2sIQa3Q',
    appId: '1:442091398232:web:b0fbba61111770bb24562d',
    messagingSenderId: '442091398232',
    projectId: 'farmer-market-ee034',
    authDomain: 'farmer-market-ee034.firebaseapp.com',
    storageBucket: 'farmer-market-ee034.firebasestorage.app',
    measurementId: 'G-8BT6EPY8X7',
  );
}
